### ISSUE TITLE
[Critical][lunarsoil_big_world] Steam deck

### ISSUE THREAD

**Issue by morgondag** [MorgondagDev/lunar-soil-tracker#59]
![https://lunar-soil-screenshots.morgondag.io/85f1dd4044fc204e51db4db623af316e.png](https://lunar-soil-screenshots.morgondag.io/85f1dd4044fc204e51db4db623af316e.png)

**💬Description:**
I need to install Proton-GE to even launch the game on a Steam Deck so you might need to fix that because the average player probally will think that the game is just broken

**⚙️Ticket-ID:** 85f1dd4044fc204e51db4db623af316e

👨‍🚀: Luca333399

**⚠️Severity:** Critical

**🗺️Level:** lunarsoil_big_world

**📍Player Position:**
X=179570.115 Y=226040.834 Z=28460.465

**⏲️Gametime & FPS Delta**
836.390625 - 35.42418670654297

---

⚙️ 0.0.7.0 - 5.2.0-25360045+++UE5+Release-5.2 - 76561199134762662 - 
⚙️ GenericGPUBrand - AMD Custom APU 0405 
*⚙️Generated from a in-game report*
*⏲️Mon May 29 2023 18:50:18 GMT+0000 (Coordinated Universal Time)*

**Comment by Sanaki** [comment]
Game launches on proton 8 just fine. The default seems to attempt to launch via Linux native, which fails immediately.
