### ISSUE TITLE
Altered camera control

### ISSUE THREAD

**Issue by morgondag** [MorgondagDev/lunar-soil-tracker#65]
![https://lunar-soil-screenshots.morgondag.io/7617aa834579d0da45393aa1217f23c2.png](https://lunar-soil-screenshots.morgondag.io/7617aa834579d0da45393aa1217f23c2.png)

**💬Description:**
The camera seems somewhat janky, making it somewhat annoying to traverse simply due to the camera acting strange. My main recommendation would be to add a zoom and expand feature, allowing the player to either move the camera closer to the character or father instead of having it at a single fixed distance. It would enable smoother gameplay while also allowing players to be able to enjoy the scenery more by having control over their field of vision. 

**⚙️Ticket-ID:** 7617aa834579d0da45393aa1217f23c2

👨‍🚀: Child of the Grapes

**🗺️Level:** lunarsoil_big_world

**📍Player Position:**
X=178599.768 Y=225748.738 Z=28459.735

**⏲️Gametime & FPS Delta**
318.92705 - 26.665102005004883

---

⚙️ 0.0.7.0 - 5.2.0-25360045+++UE5+Release-5.2 - 76561198277975360 - 
⚙️ GenericGPUBrand - 12th Gen Intel(R) Core(TM) i5-1235U 
*⚙️Generated from a in-game report*
*⏲️Mon May 29 2023 19:47:00 GMT+0000 (Coordinated Universal Time)*

**Comment by Sanaki** [comment]
As a steam deck user, massively increased camera speed is a must as well. I had to turn X axis camera sensitivity to 100% to get to a bearable speed, and even then it was a bit slow.

**Comment by morgondag** [comment]
yeah camera speed https://github.com/MorgondagDev/lunar-soil-tracker/issues/54
I think we will separate gamepad and mouse so we can crank up the gamepad one higher. (PC player wanted lower as mouse-acceleration is way different).

**Comment by Sanaki** [comment]
Understandable.

**Comment by morgondag** [comment]
Zoom controls and gamepad speed will be in the next patch.
